// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaLBSG8XzVsiO6tXiMo5NwITWFyXZDSxo',
    appId: '1:902520098501:android:d4f63787475027e6d8aaac',
    messagingSenderId: '902520098501',
    projectId: 'caffeeapp-b8412',
    databaseURL: 'https://caffeeapp-b8412-default-rtdb.firebaseio.com',
    storageBucket: 'caffeeapp-b8412.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVPXqalr5E6EyQgjSJ6rOolpk7B0ltv_o',
    appId: '1:902520098501:ios:05592925fc8a22b3d8aaac',
    messagingSenderId: '902520098501',
    projectId: 'caffeeapp-b8412',
    databaseURL: 'https://caffeeapp-b8412-default-rtdb.firebaseio.com',
    storageBucket: 'caffeeapp-b8412.appspot.com',
    iosBundleId: 'by.bsuir.cafetopiaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLk2BOoraN6F-Xcv58tsePrVCJRnPqII4',
    appId: '1:902520098501:web:bda9824f6fe69200d8aaac',
    messagingSenderId: '902520098501',
    projectId: 'caffeeapp-b8412',
    authDomain: 'caffeeapp-b8412.firebaseapp.com',
    databaseURL: 'https://caffeeapp-b8412-default-rtdb.firebaseio.com',
    storageBucket: 'caffeeapp-b8412.appspot.com',
    measurementId: 'G-70TTD8QY8S',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLk2BOoraN6F-Xcv58tsePrVCJRnPqII4',
    appId: '1:902520098501:web:6deeb87555b4eb38d8aaac',
    messagingSenderId: '902520098501',
    projectId: 'caffeeapp-b8412',
    authDomain: 'caffeeapp-b8412.firebaseapp.com',
    databaseURL: 'https://caffeeapp-b8412-default-rtdb.firebaseio.com',
    storageBucket: 'caffeeapp-b8412.appspot.com',
    measurementId: 'G-LZ87VBS5D9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVPXqalr5E6EyQgjSJ6rOolpk7B0ltv_o',
    appId: '1:902520098501:ios:650750444e53eda7d8aaac',
    messagingSenderId: '902520098501',
    projectId: 'caffeeapp-b8412',
    databaseURL: 'https://caffeeapp-b8412-default-rtdb.firebaseio.com',
    storageBucket: 'caffeeapp-b8412.appspot.com',
    iosBundleId: 'com.example.app',
  );

}